server:
    port: 8080
    tomcat:
        uri-encoding: UTF-8

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  application:
    name: ServiceAdmin
  boot:
    admin:
      notify:
        line:
          enabled: true
          channelSecret: 'fdfa7381536ba9380268b0808733c344'
          channelToken: 'UShFzDZGIRVE0Wn8+b7ZntGhgV3yOjWI+VmMnIEAzhmdMfJOfYQb/Ufcqcwqr34Z7peiEUByXd8Z+0SZbMu1mhiint6UpTL8+FXU+zpVl/3Er/f33Id38UnbFc9aIbMA/U3T1jHifNZOHPbhwvej5QdB04t89/1O/w1cDnyilFU='
          to: 'U2dbb348e5a46eb147511a26f0ef6f083'  profiles:    active: '@profile.active@'
line:
  messages:
    originalContentUrl: 'https://yt3.ggpht.com/a/AATXAJyDkD6dAgxqSk232OgBeW12_meiJgSI2pw7A9NBog=s900-c-k-c0x00ffffff-no-rj'
    previewImageUrl: 'https://yt3.ggpht.com/a/AATXAJyDkD6dAgxqSk232OgBeW12_meiJgSI2pw7A9NBog=s900-c-k-c0x00ffffff-no-rj'
    thumbnailImageUrl: 'https://play-lh.googleusercontent.com/i_KEGjIAYqatVluupykgNlrJMbUFiDh5ADQFO1b2ANolZYa5huKc3PGBUcduUZxTC7D6'
    uri: 'https://store.line.me/stickershop/home/general/zh-Hant'
facebook:
  messages:
    pageAccessToken: 'EAAVj9zXaV1gBAPYBwmlVuOEYvdfc5ylzgpHeTZB4ZBxxOlPCB5rclDScGdoZCNAdZA8ij2nm7cHQ9pkkzFLtGYisdouQ9AeKJoOZChhPIXfb3oTZC2LGuFiFX3vsJbLt3YQyzgfEL0VhZBQgLCZCUmnkC0641Cl28oP2nCd8kMPowwZDZD'

logging:
    logback:
        rollingpolicy:
            max-history: 30
            max-file-size: 3MB
            file-name-pattern: log/webhook.%d{yyyy-MM-dd}.%i.log
    file:
        name: log/webhook.log
        max-size: 3MB
        max-history: 30
    level:
        com.example.demo: trace
        com.example.demo.service: trace
        org:
            springframework:
                web:
                    client:
                        RestTemplate: DEBUG
        root: INFO
    pattern:
        console: '%d{yyyy/MM/dd HH:mm:ss} [%thread] %-5level %logger{50}.%M [%line]
            - %msg%n'
        file: '%d{yyyy/MM/dd HH:mm:ss} == [%thread] == %-5level == %logger{50}.%M
            == - %msg%n' 

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    com.howtodoinjava: DEBUG
#    org.hibernate: ERROR