spring:
  application:
    name: ServiceAdmin
  boot:
    admin:
      notify:
        line:
          enabled: true
          channelSecret: 'fdfa7381536ba9380268b0808733c344'
          channelToken: 'UShFzDZGIRVE0Wn8+b7ZntGhgV3yOjWI+VmMnIEAzhmdMfJOfYQb/Ufcqcwqr34Z7peiEUByXd8Z+0SZbMu1mhiint6UpTL8+FXU+zpVl/3Er/f33Id38UnbFc9aIbMA/U3T1jHifNZOHPbhwvej5QdB04t89/1O/w1cDnyilFU='
          to: 'U2dbb348e5a46eb147511a26f0ef6f083'
line:
  messages:
    originalContentUrl: 'https://yt3.ggpht.com/a/AATXAJyDkD6dAgxqSk232OgBeW12_meiJgSI2pw7A9NBog=s900-c-k-c0x00ffffff-no-rj'
    previewImageUrl: 'https://yt3.ggpht.com/a/AATXAJyDkD6dAgxqSk232OgBeW12_meiJgSI2pw7A9NBog=s900-c-k-c0x00ffffff-no-rj'
    thumbnailImageUrl: 'https://play-lh.googleusercontent.com/i_KEGjIAYqatVluupykgNlrJMbUFiDh5ADQFO1b2ANolZYa5huKc3PGBUcduUZxTC7D6'
    uri: 'https://store.line.me/stickershop/home/general/zh-Hant'
facebook:
  messages:
    pageAccessToken: 'EAAVj9zXaV1gBAFalmhGchV4dSERFiubQQaYIoqePj1Ko5CSZAXcV5j1yfaf7Y43jyqTVYyvXwGkSvI8XMPjIvKLtBWf3lqIBgsAxZBXrYD3MhURtHfQNmrNhZB3WFr6hFpABQvOKmogRePK7d7UgxUpa7ZAOSkDcQxENZATsSneYcCIz5B1y1'
#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    com.howtodoinjava: DEBUG
#    org.hibernate: ERROR